LR/config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index', as: :admin_page
  get 'users_workouts/buy/:id', to: 'users_workouts#buy', as: :users_workouts_buy
  get 'users_workouts/cancel/:id', to: 'users_workouts#cancel', as: :users_workouts_cancel
  resources :workouts
  root 'home#index'
  get 'dashboard', to: 'home#dashboard', as: 'dashboard'

  get 'home/profile', to: 'home#profile', as: :profile
  get 'home/index'
  get 'home/dashboard'
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

LR/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

LR/app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :workouts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable,
  :timeoutable

  validates :first_name, :last_name, presence: true, length: { maximum: 30, minimum: 3 }
  validates :email, email: {mode: :strict}, length: { maximum: 50, minimum: 7 }

  def admin?
    role == "admin"
  end
  
end

LR/app/models/workout.rb
class Workout < ApplicationRecord
    has_and_belongs_to_many :users
end

LR/app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def index
      @workouts = Workout.all
      authorize Workout, policy_class: AdminPolicy
    rescue Pundit::NotAuthorizedError
      redirect_to root_path
    end
  end

LR/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    include Pundit::Authorization
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

LR/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
    before_action :authenticate_user!, only: [:profile]
  
    def index
      redirect_to workouts_path
    end
  
    def profile
      @current_user = current_user
      @workouts = current_user.workouts
    end
  end

LR/app/controllers/users_workouts_controller.rb
class UsersWorkoutsController < ApplicationController
    before_action :authenticate_user!
  
    def buy
      workout = Workout.find params[:id]
      unless current_user.workouts.where(id: params[:id]).any?
        current_user.workouts << workout
      end
      redirect_to workout
    end
  
    def cancel
      workout = Workout.find params[:id]
      if current_user.workouts.where(id: params[:id]).any?
        current_user.workouts.delete workout.id
      end
      redirect_to workout
    end
  end

LR/app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

        def index
          @workouts = Workout.all
        end
      
        
        def show
          @user_buy_current_workout = user_signed_in? && current_user.workouts.where(id: params[:id]).any?
          @workout = Workout.find(params[:id])
        end
      
     
        def new
          @workout = Workout.new
          authorize @workout
        rescue Pundit::NotAuthorizedError
          redirect_to root_path
        end
      
       
        def edit
          @workout = Workout.find(params[:id])
          authorize @workout
        rescue Pundit::NotAuthorizedError
          redirect_to root_path
        end
      
        def create
          @workout = Workout.new(workout_params)
      
          respond_to do |format|
            if @workout.save
              format.html { redirect_to :admin_page, notice: "Тренировка была успешно создана." }
              format.json { render :show, status: :created, location: @workout }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @workout.errors, status: :unprocessable_entity }
            end
          end
        end
      
       
        def update
          @workout = Workout.find(params[:id])
          respond_to do |format|
            if @workout.update(workout_params)
              format.html { redirect_to :admin_page, notice: "Тренировка была успешно обновлена." }
              format.json { render :show, status: :ok, location: @workout }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @workout.errors, status: :unprocessable_entity }
            end
          end
        end
      
   
        def destroy
          @workout = Workout.find(params[:id])
          begin
            authorize @workout
          rescue Pundit::NotAuthorizedError
            redirect_to root_path
            return
          end
            
            @workout.destroy
      
            respond_to do |format|
                format.html { redirect_to workouts_url, notice: "Тренировка была успешно удалена." }
                format.json { head :no_content }
            end
        end
      
        private
      
    
        def set_workout
          @workout = Workout.find(params[:id])
        end
      
        
        def workout_params
          params.require(:workout).permit(:title, :descriprtion)
        end
    
end

LR/app/helpers/application_helper.rb
module ApplicationHelper
end

LR/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

LR/app/views/admin/index.html.erb
<%= link_to 'Главная', workouts_path %>

<h1>Админ</h1>

<%= link_to 'Новая тренировка', new_workout_path %>

<h1>Все тренировки</h1>

<div id="workouts">
  <% @workouts.each do |workout| %>
    <%= render workout %>
    <p>
      <%= link_to "Подробнее", workout %>
      <%= link_to "Редактировать", edit_workout_path(workout) %>
      <%= button_to "Удалить тренировку", workout, method: :delete %>
    </p>
  <% end %>
</div>

LR/app/views/home/index.html.erb
<h1>Body Balance</h1>
<p>Добро пожаловать!</p>

<% if user_signed_in? %>
<span>Здравствуйте, <%= current_user.email %></span>
<%= link_to 'Выйти', destroy_user_session_path, data: { turbo_method: :delete } %>
<%= link_to 'Редактировать профиль', edit_user_registration_path %>

<% else %>
<%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

LR/app/views/home/profile.html.erb
<div class="profile">

  <%= link_to 'Главная', workouts_path %>

  <h1>Мой профиль</h1>

  <p>
    <strong>ФИО:</strong>
    <%= @current_user.first_name %> <%= @current_user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @current_user.email %>
  </p>

  <%= button_to "Выход", destroy_user_session_path, id: current_user.id, method: :delete, class:"delete" %>

  <h2>Мои тренировки</h2>

  <div id="workouts">
    <% @workouts.each do |workout| %>
      <%= render workout %>
      <p>
        <%= link_to "Подробнее", workout %>
      </p>
    <% end %>
  </div>
</div>

LR/app/views/home/user.html.erb
<h1>Профиль</h1>


<% if user_signed_in? %>
<span>Здравствуйте, <%= current_user.first_name %> <%= current_user.last_name %></span>
<%= link_to 'Выйти', destroy_user_session_path, data: { turbo_method: :delete } %>
<%= link_to 'Редактировать профиль', edit_user_registration_path %>

<% else %>
Вы не авторизованы!
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

LR/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BodyBalanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

LR/app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |form| %>
   
  
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :descriprtion, style: "display: block" %>
      <%= form.text_field :descriprtion %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

LR/app/views/workouts/_workout.html.erb
<div id="<%= dom_id workout %>">
  <p>
    <strong>Название:</strong>
    <%= workout.title %>
  </p>

  <p>
    <strong>Описание:</strong>
    <%= workout.descriprtion %>
  </p>

</div>

LR/app/views/workouts/edit.html.erb
<h1>Редактировать тренировку</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Подробнее", @workout %> |
  <%= link_to "Вернуться ко всем тренировкам", workouts_path %>

LR/app/views/workouts/index.html.erb
<%= link_to 'Мой профиль', profile_path %>
<%= link_to 'Админ', :admin_page %>

<h1>Все тренировки</h1>

<div id="workouts">
  <% @workouts.each do |workout| %>
    <%= render workout %>
    <p>
      <%= link_to "Подробнее", workout %>
    </p>
  <% end %>
</div>

LR/app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Вернуться ко всем тренировкам", workouts_path %>
</div>

LR/app/views/workouts/show.html.erb
<%= render @workout  %>

<div>
  <% if @user_buy_current_workout %>
    <%= link_to "Отказаться от тренировки", users_workouts_cancel_path(@workout) %> |
  <% else %>
    <%= link_to "Купить", users_workouts_buy_path(@workout) %> |
<% end %>
  <%= link_to "Вернуться ко всем тренировкам", workouts_path %>

</div>